name: Convert notebooks to Markdown

on: [workflow_dispatch]

jobs:
  convert-notebooks:
    name: Convert notebooks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - run: poetry install --with dev

      - name: Convert notebooks
        run: poetry run python .scripts/convert-all-notebooks-to-hugo-markdown.py
