name: Pull request notebooks to landing page

on:
  pull_request:
    types: [ closed ]
#    branches:
#      - main
#      - master
    paths:
      - '**.ipynb'

jobs:
  convert-notebooks:
    name: Convert notebooks
    runs-on: ubuntu-latest

    # This job will only run if the PR has been merged
    if: github.event.pull_request.merged == true

    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - run: poetry install --with dev

      - name: Convert notebooks
        run: poetry run python .scripts/convert-all-notebooks-to-hugo-markdown.py

      - name: Pull Request landing page repository
        uses: car-on-sale/action-pull-request-another-repo@v1.3.1
        env:
          API_TOKEN_GITHUB: ${{ env.GITHUB_TOKEN }}
        with:
          source_folder: '.dist'
          destination_repo: 'kacperlukawski/landing_page'
          destination_folder: 'qdrant-landing/content/documentation'
          destination_base_branch: 'master'
          destination_head_branch: ${{ env.GITHUB_HEAD_REF }}
          user_email: ${{ github.event.pull_request.user.email }}
          user_name: ${{ github.event.pull_request.user.login }}
          pr_title: ${{ github.event.pull_request.title }}
