name: Pull request notebooks to landing page

on:
  pull_request:
    types: [ closed ]
#    branches:
#      - main
#      - master
    paths:
      - '**.ipynb'

jobs:
  convert-notebooks:
    name: Convert notebooks
    runs-on: ubuntu-latest

    # This job will only run if the PR has been merged
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          path: 'current-repo'

      - name: Checkout landing page repository
        uses: actions/checkout@v4
        with:
          repository: kacperlukawski/landing_page
          path: 'landing-page'

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - run: poetry install --with dev

      - name: Convert notebooks
        run: poetry run python .scripts/convert-all-notebooks-to-hugo-markdown.py
