name: Pull request notebooks to landing page

on:
  pull_request:
    types: [ closed ]
#    branches:
#      - main
#      - master
    paths:
      - '**.ipynb'

jobs:
  convert-notebooks:
    name: Convert notebooks
    runs-on: ubuntu-latest

    # This job will only run if the PR has been merged
    if: github.event.pull_request.merged == true

    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - run: poetry install --with dev

      - name: Convert notebooks
        run: poetry run python .scripts/convert-all-notebooks-to-hugo-markdown.py

      - name: Pull Request landing page repository
        uses: harrietrs/copy-to-pr@v1.0.0
        env:
          GH_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          destination_owner: 'kacperlukawski'
          destination_repo: 'landing_page'
          source_directory: '.dist'
          destination_directory: 'qdrant-landing/content/documentation'
          destination_base_branch: 'master'
